kind: Secret
apiVersion: v1
metadata: 
  name: githubsecret
data:
  WebHookSecretKey: c3VwZXJzZWNyZXQK
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-ocp-build
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/nishant-jain-94/hello-nodejs-ocp'
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: supersecret